[package]
name = "hydro-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
numpy = "0.27"
pyo3 = { version = "0.27", features = ["extension-module"] }
pyo3-stub-gen = "0.17"

[lib]
name = "hydro_rs"
crate-type = ["cdylib", "rlib"]

[lints.rust]
non_upper_case_globals = "allow"
