[package]
name = "hydro-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
numpy = "0.27.1"
pyo3 = { version = "0.27.2", features = ["extension-module"] }

[lib]
name = "hydro_rs"
crate-type = ["cdylib"]
