[project]
name = "hydro-rs"
version = "0.1.0"
requires-python = ">=3.13"

[build-system]
requires = ["maturin>=1.10.2"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "hydro_rs"
